// Custom plugin: pre-renames `const require = createRequire(...)` to
// `const _cjsRequire = createRequire(...)` before other plugins run.
// This prevents a conflict with @babel/plugin-transform-modules-commonjs:
// when that plugin sees a local `const require` binding, it renames ALL
// `require` references in scope to `_require` — including the `require()`
// calls that babel-plugin-transform-import-meta generates for import.meta.url.
// This results in `_require('url')` appearing in the RHS of `const _require`,
// causing a TDZ ReferenceError at runtime.
// By pre-renaming the local binding to `_cjsRequire`, there is no longer any
// `require` binding conflict and all generated `require()` calls remain valid.
function preRenameLocalRequireBinding({ types: t }) {
  return {
    visitor: {
      // If a file declares `const require = ...` at the top-level program
      // scope, rename that binding to `_cjsRequire` before other plugins run.
      // This prevents @babel/plugin-transform-modules-commonjs from renaming
      // ALL `require` references (including those generated by
      // babel-plugin-transform-import-meta) which would cause a TDZ error.
      Program(programPath) {
        const binding = programPath.scope.getBinding("require");
        if (binding && binding.kind === "const") {
          programPath.scope.rename("require", "_cjsRequire");
        }
      },
    },
  };
}

module.exports = {
  plugins: [
    preRenameLocalRequireBinding,
    "babel-plugin-transform-import-meta",
    ["@babel/plugin-transform-modules-commonjs", { allowTopLevelThis: true }],
  ],
};
